### ISSUE TITLE
Unable to install 

### ISSUE THREAD

**Issue by SDSilicus** [amida-tech/blue-button#243]
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i
nstall" "blue-botton"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/blue-botton
npm ERR! 404
npm ERR! 404 'blue-botton' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\12 SandBox\Node\npm-debug.log
PS D:\12 SandBox\Node> npm install https://github.com/SDSilicus/blue-button.git
|

![image](https://cloud.githubusercontent.com/assets/13151580/11035785/7bb647ee-871a-11e5-8b2c-b0819a9fe973.png)

**Comment by jsachs** [comment]
Hi @SDSilicus,

It appears that you typed `blue-botton` instead of `blue-button`. I think that will fix the issue for you.

**Comment by SDSilicus** [comment]
Thank you @jsachs   But it is not working i have correct my typing mistake
![image](https://cloud.githubusercontent.com/assets/13151580/11038246/fcba99c8-8727-11e5-862f-f03f16481f54.png)

**Comment by jsachs** [comment]
@SDSilicus please try to work through your error messages before opening an issue. NPM is telling you that it cannot find a python executable. Either you do not have python installed, or the python executable isn't in your PATH.

I do not believe this issue is related to the actual `blue-button` module.
