### ISSUE TITLE
Security vulnerability in moment dependency

### ISSUE THREAD

**Issue by avindra** [amida-tech/blue-button#253]
Please see https://github.com/amida-tech/blue-button-cms/pull/10 for more details.

TL;DR, the version of `moment` being pinned in `blue-button-cms` has a security vulnerability that is being flagged by security scanners, preventing people from using this library.

**Comment by jsachs** [comment]
Closed by https://github.com/amida-tech/blue-button-cms/pull/10

**Comment by avindra** [comment]
That was quick, thank you @jsachs!
