### ISSUE TITLE
performers in medication do not conform to model

### ISSUE THREAD

**Issue by psalaets** [amida-tech/blue-button#261]
# Background

There can be two performers in a medication record:

- `medication.performer`
- `medication.dispense.performer`

and both parse `phone` as a `0..1` ([see here](https://github.com/amida-tech/blue-button/blob/master/lib/parser/ccda/sections/medications.js#L119)) field.

# Problem

In the model, `phone` is supposed to be an array.

See

- `medication.performer` is a `cda_performer` as defined at [medication model line 234](https://github.com/amida-tech/blue-button-model/blob/master/lib/schemas/medication.js#L234)
- `medication.dispense.performer` is a `cda_performer` as defined at [medication model line 250](https://github.com/amida-tech/blue-button-model/blob/master/lib/schemas/medication.js#L250)
- `phone` definition within the `cda_performer` definition at [common models line 291](https://github.com/amida-tech/blue-button-model/blob/master/lib/schemas/common_models.js#L291)

# Invalid document

When I run the example in the README and print out `bb.validator.lastError`, it contains some related errors

```
{
    code: 'INVALID_TYPE',
    params: [ 'array', 'object' ],
    message: 'Expected type array but found type object',
    path: '#/data/medications/0/dispense/performer/phone',
    schemaId: 'document_model'
}
```

and

```
{
    code: 'INVALID_TYPE',
    params: [ 'array', 'object' ],
    message: 'Expected type array but found type object',
    path: '#/data/medications/0/performer/phone',
    schemaId: 'document_model'
}
```

If this is a legit issue and I'm not overlooking something, are you open to accepting a PR with the fix? I would change the phone's `0..1` to `0..*`.

**Comment by Manhydra** [comment]
@psalaets Yes, send a PR for this issue when ready.
